sudo: false
language: python
services:
  - docker
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
  - "nightly"  # nightly build
before_install:
  - docker run -d -p 127.0.0.1:4100:4100 pafortin/goaws
install:
  - pip install -U boto3 codecov -r requirements-test.txt
script:
  - coverage run -m pytest
after_success:
  - codecov
